"""
PLUTON V2 — Canonical Computer Control Protocols & Interface Contracts
Defines runtime Protocols for all 12 computer control domains and low-level engines.
Every domain handler and concrete engine MUST implement its corresponding Protocol.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


class CanonicalInterfaceError(RuntimeError):
    """Raised when a computer engine fails interface conformance verification."""
    pass


# -----------------------------------------------------------------------------
# 1. Window & UI Automation Protocols
# -----------------------------------------------------------------------------

@runtime_checkable
class IWindowDomain(Protocol):
    """Protocol for Window lifecycle and state manipulation."""

    def list_windows(self, visible_only: bool = True, context: Any = None) -> list[dict[str, Any]]: ...
    def find_window(self, target: str | int, context: Any = None) -> dict[str, Any] | None: ...
    def get_foreground_window(self, context: Any = None) -> dict[str, Any]: ...
    def focus_window(self, target: str | int, context: Any = None) -> dict[str, Any]: ...
    def close_window(self, target: str | int, context: Any = None) -> dict[str, Any]: ...
    def window_state(self, target: str | int | None = None, context: Any = None) -> dict[str, Any]: ...


@runtime_checkable
class IUIAEngine(Protocol):
    """Protocol for UI Automation Engine and low-level accessibility interactions."""

    def list_windows(self, visible_only: bool = True) -> list[dict[str, Any]]: ...
    def find_window(self, query: str) -> dict[str, Any] | None: ...
    def get_foreground_window(self) -> dict[str, Any]: ...
    def focus_window(self, hwnd: int) -> bool: ...
    def close_window(self, hwnd: int) -> bool: ...
    def window_state(self, hwnd: int) -> dict[str, Any]: ...
    def inspect_tree(self, hwnd: int | None = None, max_depth: int = 4) -> dict[str, Any]: ...
    def find_element(self, query: str, hwnd: int | None = None, control_type: str | None = None) -> dict[str, Any] | None: ...
    def find_elements(self, query: str, hwnd: int | None = None, control_type: str | None = None) -> list[dict[str, Any]]: ...
    def invoke(self, element_id: str | int, hwnd: int | None = None) -> dict[str, Any]: ...
    def set_value(self, element_id: str | int, value: str, hwnd: int | None = None) -> dict[str, Any]: ...
    def toggle(self, element_id: str | int, hwnd: int | None = None) -> dict[str, Any]: ...
    def select(self, element_id: str | int, value: str | None = None, hwnd: int | None = None) -> dict[str, Any]: ...
    def expand_collapse(self, element_id: str | int, expand: bool = True, hwnd: int | None = None) -> dict[str, Any]: ...
    def focus(self, element_id: str | int, hwnd: int | None = None) -> dict[str, Any]: ...


@runtime_checkable
class IUIDomain(Protocol):
    """Protocol for semantic UI element domain handler."""

    def inspect_tree(self, hwnd: int = 0, depth: int = 4, context: Any = None) -> list[dict[str, Any]] | dict[str, Any]: ...
    def find_element(self, query: str, hwnd: int = 0, control_type: str | None = None, context: Any = None) -> dict[str, Any] | None: ...
    def find_elements(self, query: str, hwnd: int = 0, control_type: str | None = None, context: Any = None) -> list[dict[str, Any]]: ...
    def invoke(self, target: str, hwnd: int = 0, context: Any = None) -> dict[str, Any]: ...
    def set_value(self, target: str, value: str, hwnd: int = 0, context: Any = None) -> dict[str, Any]: ...
    def toggle(self, target: str, hwnd: int = 0, context: Any = None) -> dict[str, Any]: ...
    def select(self, target: str, hwnd: int = 0, context: Any = None) -> dict[str, Any]: ...
    def expand_collapse(self, target: str, expand: bool = True, hwnd: int = 0, context: Any = None) -> dict[str, Any]: ...
    def focus(self, target: str, hwnd: int = 0, context: Any = None) -> dict[str, Any]: ...


IUIADomain = IUIDomain


# -----------------------------------------------------------------------------
# 2. Browser & Web Protocols
# -----------------------------------------------------------------------------

@runtime_checkable
class IBrowserDomain(Protocol):
    """Protocol for Browser lifecycle, tab management, and navigation."""

    def detect(self, browser_name: str = "Brave", context: Any = None) -> dict[str, Any]: ...
    def list_tabs(self, browser_name: str = "Brave", browser: str | None = None, context: Any = None) -> list[dict[str, Any]]: ...
    def create_tab(self, url: str = "about:blank", browser_name: str = "Brave", browser: str | None = None, context: Any = None) -> Any: ...
    def switch_tab(self, target: str | int, browser_name: str = "Brave", browser: str | None = None, context: Any = None) -> Any: ...
    def close_tab(self, target: str | int | None = None, browser_name: str = "Brave", browser: str | None = None, context: Any = None) -> Any: ...
    def navigate(self, url: str, browser_name: str = "Brave", browser: str | None = None, context: Any = None) -> Any: ...
    def get_title(self, browser_name: str = "Brave", context: Any = None) -> dict[str, Any]: ...
    def get_url(self, browser_name: str = "Brave", context: Any = None) -> dict[str, Any]: ...


@runtime_checkable
class IWebDomain(Protocol):
    """Protocol for semantic Webpage DOM interaction and content extraction."""

    def inspect(self, max_elements: int = 150, context: Any = None) -> Any: ...
    def find(self, target: str, role: str | None = None, context: Any = None) -> Any: ...
    def click(self, target: str, role: str | None = None, expected_change: str | None = None, context: Any = None) -> Any: ...
    def type(self, target: str, text: str, role: str | None = None, clear_first: bool = False, press_enter: bool = False, context: Any = None) -> Any: ...
    def select(self, target: str, value: str, role: str | None = None, context: Any = None) -> Any: ...
    def read(self, target: str | None = None, selector: str | None = None, max_length: int = 4000, context: Any = None) -> Any: ...
    def extract(self, target: str | None = None, selector: str | None = None, max_length: int = 4000, context: Any = None) -> Any: ...


# -----------------------------------------------------------------------------
# 3. Input & Peripherals Protocols
# -----------------------------------------------------------------------------

@runtime_checkable
class IKeyboardDomain(Protocol):
    """Protocol for verified target-bound keyboard input."""

    def type(self, text: str, hwnd: int = 0, pid: int = 0, target: str | None = None, target_window: str | None = None, expected_text: str | None = None, context: Any = None, **kwargs: Any) -> dict[str, Any]: ...
    def press(self, key: str, context: Any = None) -> dict[str, Any]: ...
    def hotkey(self, keys: list[str] | str, context: Any = None) -> dict[str, Any]: ...
    def copy(self, context: Any = None) -> dict[str, Any]: ...
    def paste(self, context: Any = None) -> dict[str, Any]: ...


@runtime_checkable
class IMouseDomain(Protocol):
    """Protocol for mouse pointer and button interactions."""

    def move(self, x: int, y: int, context: Any = None) -> dict[str, Any]: ...
    def click(self, x: int | None = None, y: int | None = None, button: str = "left", clicks: int = 1, target_description: str | None = None, context: Any = None) -> dict[str, Any]: ...
    def double_click(self, x: int | None = None, y: int | None = None, target_description: str | None = None, context: Any = None) -> dict[str, Any]: ...
    def right_click(self, x: int | None = None, y: int | None = None, target_description: str | None = None, context: Any = None) -> dict[str, Any]: ...
    def drag(self, start_x: int = 0, start_y: int = 0, end_x: int = 0, end_y: int = 0, source_target: str | None = None, destination_target: str | None = None, context: Any = None, **kwargs: Any) -> dict[str, Any]: ...
    def scroll(self, clicks: int = 0, x: int | None = None, y: int | None = None, context: Any = None) -> dict[str, Any]: ...


# -----------------------------------------------------------------------------
# 4. Screen, Vision, Filesystem, Terminal, Clipboard Protocols
# -----------------------------------------------------------------------------

@runtime_checkable
class IScreenDomain(Protocol):
    """Protocol for screen capture and display metrics."""

    def capture(self, region: tuple[int, int, int, int] | None = None, context: Any = None) -> dict[str, Any]: ...
    def inspect(self, region: tuple[int, int, int, int] | None = None, context: Any = None) -> dict[str, Any]: ...


@runtime_checkable
class IVisionDomain(Protocol):
    """Protocol for visual grounding, inspection, and verification."""

    def locate(self, target_description: str, confidence: float = 0.8, context: Any = None) -> dict[str, Any]: ...
    def inspect(self, prompt: str, image: Any = None, context: Any = None) -> dict[str, Any]: ...
    def compare(self, image_a_b64: str, image_b_b64: str, context: Any = None) -> dict[str, Any]: ...
    def verify(self, expected_visual_state: str, context: Any = None) -> dict[str, Any]: ...


@runtime_checkable
class IFilesystemDomain(Protocol):
    """Protocol for verified file and directory operations."""

    def list(self, path: str = ".", context: Any = None) -> dict[str, Any]: ...
    def read(self, path: str, context: Any = None) -> dict[str, Any]: ...
    def write(self, path: str, content: str, append: bool = False, context: Any = None) -> dict[str, Any]: ...
    def create(self, path: str, is_dir: bool = False, context: Any = None) -> dict[str, Any]: ...
    def move(self, source: str, destination: str, context: Any = None) -> dict[str, Any]: ...
    def copy(self, source: str, destination: str, context: Any = None) -> dict[str, Any]: ...
    def rename(self, source: str, new_name: str, context: Any = None) -> dict[str, Any]: ...
    def delete(self, path: str, recursive: bool = False, context: Any = None) -> dict[str, Any]: ...
    def exists(self, path: str, context: Any = None) -> dict[str, Any]: ...


@runtime_checkable
class ITerminalDomain(Protocol):
    """Protocol for command execution in OS terminal/shell."""

    def execute(self, command: str, cwd: str | None = None, timeout: float = 30.0, context: Any = None, allow_high_risk: bool = False) -> dict[str, Any]: ...
    def output(self, task_id: str | None = None, context: Any = None) -> dict[str, Any]: ...
    def exit_code(self, task_id: str | None = None, context: Any = None) -> dict[str, Any]: ...
    def process(self, pid: int | None = None, context: Any = None) -> dict[str, Any]: ...
    def stop(self, pid: int, context: Any = None) -> dict[str, Any]: ...


@runtime_checkable
class IClipboardDomain(Protocol):
    """Protocol for system clipboard operations."""

    def get(self, context: Any = None) -> dict[str, Any]: ...
    def set(self, content: str, context: Any = None) -> dict[str, Any]: ...
    def clear(self, context: Any = None) -> dict[str, Any]: ...


@runtime_checkable
class IAppDomain(Protocol):
    """Protocol for native desktop application lifecycle."""

    def list(self, context: Any = None) -> list[dict[str, Any]]: ...
    def launch(self, app_name: str, args: list[str] | None = None, reuse_existing: bool = False, context: Any = None) -> dict[str, Any]: ...
    def focus(self, app_name: str, context: Any = None) -> dict[str, Any]: ...
    def close(self, app_name: str, context: Any = None) -> dict[str, Any]: ...
    def is_running(self, app_name: str, context: Any = None) -> dict[str, Any]: ...
