"""PLUTON V2 Canonical Artifact Management.

Manages structured artifacts generated by agent tasks (files, diffs, reports, research logs).
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from ..config import get_settings
from ..core.contracts import Artifact, ArtifactType

logger = logging.getLogger("pluton.artifacts")


class ArtifactManager:
    """Canonical artifact storage and retrieval engine."""

    def __init__(self, base_dir: Path | None = None) -> None:
        self._base_dir = base_dir

    @property
    def base_dir(self) -> Path:
        if self._base_dir is None:
            settings = get_settings()
            p = Path(settings.allowed_workspace) / "data" / "artifacts"
            p.mkdir(parents=True, exist_ok=True)
            self._base_dir = p
        return self._base_dir

    def store_artifact(
        self,
        task_id: str,
        name: str,
        artifact_type: ArtifactType,
        content: str | bytes,
        summary: str = "",
        metadata: dict[str, Any] | None = None,
    ) -> Artifact:
        """Persist an artifact to disk and return the canonical Artifact model."""
        task_dir = self.base_dir / task_id
        task_dir.mkdir(parents=True, exist_ok=True)

        safe_name = "".join(c for c in name if c.isalnum() or c in "._- ")
        file_path = task_dir / safe_name

        if isinstance(content, str):
            file_path.write_text(content, encoding="utf-8")
        else:
            file_path.write_bytes(content)

        artifact = Artifact(
            name=name,
            artifact_type=artifact_type,
            task_id=task_id,
            content=content,
            file_path=str(file_path),
            summary=summary or f"{artifact_type.value.title()} artifact '{name}'",
            metadata=metadata or {},
        )
        logger.info("[ARTIFACT] Stored %s artifact '%s' for task %s at %s", artifact_type.value, name, task_id, file_path)
        return artifact

    def get_artifact_path(self, task_id: str, name: str) -> Path | None:
        """Lookup an artifact by task ID and filename."""
        safe_name = "".join(c for c in name if c.isalnum() or c in "._- ")
        file_path = self.base_dir / task_id / safe_name
        if file_path.exists():
            return file_path
        return None


ARTIFACT_MANAGER = ArtifactManager()
